apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foreign-language-reader-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - foreignlanguagereader.com
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 4000
      - path: /language/*
        backend:
          serviceName: language-service
          servicePort: 8000
