apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foreign-language-reader-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 4000
      - path: /language/*
        backend:
          serviceName: language-service
          servicePort: 8000
