# Use this to cache project dependencies for easy building
FROM lkjaero/foreign-language-reader-api:base

ARG github
ENV GITHUB_TOKEN=$github

ENV SBT_VERSION 1.3.9
ENV INSTALL_DIR /usr/local
ENV SBT_HOME /usr/local/sbt
ENV PATH ${PATH}:${SBT_HOME}/bin

WORKDIR /app

# Keep failing pipe command from reporting success to the build.
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

RUN if [ -z "$GITHUB_TOKEN" ] \
    then \
        echo "not defined" \
    else  \
        echo "defined" \
    fi \

# Install sbt
RUN apk add --no-cache wget=1.20.3-r1 && \
    mkdir -p "$SBT_HOME" && \
    wget -qO - --no-check-certificate "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" |  tar xz -C $INSTALL_DIR && \
    echo "- with sbt $SBT_VERSION" >> /root/.built

# Cache dependencies
COPY project project
COPY build-dependencies build.sbt
RUN sbt compile && \
    rm build.sbt
