# Use this to cache project dependencies for easy building
FROM lkjaero/foreign-language-reader-api:base

# Needed because sbt will barf if we don't have one
# Even though we aren't actually accessing the maven package repository
ENV GITHUB_TOKEN faketoken

ENV SBT_VERSION 1.3.9
ENV INSTALL_DIR /usr/local
ENV SBT_HOME /usr/local/sbt
ENV PATH ${PATH}:${SBT_HOME}/bin

WORKDIR /app

# Keep failing pipe command from reporting success to the build.
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

# Install sbt
RUN apk add --no-cache wget=1.21.2-r2 && \
    mkdir -p "$SBT_HOME" && \
    wget -qO - --no-check-certificate "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" |  tar xz -C $INSTALL_DIR && \
    echo "- with sbt $SBT_VERSION" >> /root/.built && \
    apk del wget

# Cache dependencies
COPY project project
COPY build-dependencies build.sbt
COPY coursier_cache /root/.cache/coursier/v1/
RUN sbt compile && \
    rm build.sbt
