# Base docker environment for builder and deployment, used for a couple of things
# - Keep all files on same os / java version
# - Perform basic setup
# - Prevent re-pulling from docker hub, to avoid rate limiting.


FROM openjdk:15-ea-jdk-alpine3.12
# This docker image isn't maintained anymore, the latest version that's still getting updates is 17.
# Unfortunately, the current guice supports java <= 16, pending this issue:
# https://github.com/google/guice/issues/1536

# This is one of many reasons why I want to drop play framework.
# But until the patch is released, I'll manually upgrade the container image.

LABEL maintainer="reader@lucaskjaerozhang.com"
WORKDIR /app
RUN apk add --no-cache bash=5.0.17-r0

