# Base docker environment for builder and deployment, used for a couple of things
# - Keep all files on same os / java version
# - Perform basic setup
# - Prevent re-pulling from docker hub, to avoid rate limiting.


FROM openjdk:15-ea-jdk-alpine3.12
# This docker image isn't maintained anymore, the latest version that's still getting updates is 17.
# Unfortunately, the current guice supports java <= 16, pending this issue:
# https://github.com/google/guice/issues/1536

# This is one of many reasons why I want to drop play framework.
# But until the patch is released, I'll manually upgrade the container image.

LABEL maintainer="reader@lucaskjaerozhang.com"
WORKDIR /app

# The play framework runners are bash scripts, so we need this to run the service.
RUN apk add --no-cache bash=5.0.17-r0

# Manually upgrade all packages to avoid security vulnerabilities
RUN apk add --upgrade apk-tools=2.10.8-r0 \
                      busybox=1.34.1-r5 \
                      libcrypto1.1=1.1.1l-r0 \
                      libssl1.1=1.1.1l-r0 \
                      ssl_client=1.31.1-r21 \
                      p11-kit=0.23.22-r0 \
                      p11-kit-trust=0.23.22-r0