version: '3'
services:
  api:
    build: ./api
    environment:
      AUTH_TOKEN: "simpletoken"
      DATABASE_URL: "ecto://dev-user:dev-password@database:33061/foreign-language-reader"
      SECRET_KEY_BASE: "KN4rxjPOfxRk3uo7fD928e6nt12jzrvy5t90fp7Snlp63ckc0rRZTglirGt+WiB6"
      LANGUAGE_SERVICE_URL: "http://localhost:8000"
    ports:
    - 4000:4000
  cache:
    image: "redis:5-buster"
    ports:
    - 6379:6379
  database:
    image: "mysql:5.7"
    environment:
      MYSQL_USER: dev-user
      MYSQL_PASSWORD: dev-password
      MYSQL_DATABASE: foreign-language-reader
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
    - 33061:3306
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
    - "discovery.type=single-node"
    ports:
    - 9200:9200
    - 9300:9300
  language-service:
    build: ./language-service
    environment:
      AUTH_TOKEN: "simpletoken"
    ports:
    - 8000:8000
