apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-service
spec:
  selector:
    matchLabels:
      app: language-service
  replicas: 1
  template:
    metadata:
      labels:
        app: language-service
    spec:
      containers:
      - name: language-service
        image: 037187302622.dkr.ecr.us-west-2.amazonaws.com/foreign-language-reader-language-service:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
