esConfig:
  elasticsearch.yml: |
    xpack:
      security:
        enabled: true
        transport:
          ssl:
            enabled: true
            verification_mode: certificate
            key: /usr/share/elasticsearch/config/certs/private_key_pem.crt
            certificate: /usr/share/elasticsearch/config/certs/certificate_pem.crt
            certificate_authorities: [ "/usr/share/elasticsearch/config/certs/issuer_pem.crt" ]

  roles.yml: |
    healthcheck:
      cluster: [ 'monitor' ]
      indices:
        - names: [ 'admin/get' ]
          privileges: [ 'get' ]
    logging:
      cluster: [ 'monitor' ]
      indices:
        - names: [ 'logstash-*' ]
          privileges: [ 'all' ]

extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username

readinessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

secretMounts:
  - name: elastic-certificates
    secretName: elasticsearch-certificates
    path: /usr/share/elasticsearch/config/certs
