apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 037187302622.dkr.ecr.us-west-2.amazonaws.com/foreign-language-reader-api:latest
        env:
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: local-connection-token
                key: local_connection_token
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api-database-credentials
                key: connection_string
          - name: LANGUAGE_SERVICE_URL
            value: http://language-service.default.svc.cluster.local:8000
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: api-secret-key-base
                key: secret_key_base
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "500Mi"
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
