apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 037187302622.dkr.ecr.us-west-2.amazonaws.com/foreign-language-reader-api:latest
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api-database-credentials
                key: connection_string
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: api-secret-key-base
                key: secret_key_base
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
