region: us-west-2

function_name: wiktionary-vocabulary-lookup
handler: service.handler
description: Wiktionary vocabulary lookup
runtime: python3.6
role: foreign-language-reader-vocabulary-lambda

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
bucket_name: 'vocabulary-lambda-deploy'
s3_key_prefix: ''

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
# timeout: 15
# memory_size: 512
# concurrency: 500
#

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
