extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: 'KIBANA_ENCRYPTION_KEY'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: encryptionkey

kibanaConfig:
  kibana.yml: |
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
