case class SimpleWiktionary(text: String,
                            examples: String,
                            noun: String,
                            expression: String,
                            homophones: String,
                            prefix: String,
                            synonyms: String,
                            symbol: String,
                            initialism: String,
                            abbreviation: String,
                            suffix: String,
                            contraction: String,
                            notes: String,
                            conjunction: String,
                            antonym: String,
                            phrases: String,
                            antonyms: String,
                            gallery: String,
                            adverb: String,
                            determiner: String,
                            usage: String,
                            synonym: String,
                            acronym: String,
                            interjection: String,
                            determinative: String,
                            preposition: String,
                            adjective: String,
                            etymology: String,
                            pronoun: String,
                            phrase: String,
                            verb: String,
                            numerals: String,
                            pronunciation: String)

object SimpleWiktionary {
  val sectionNames = List(
    "Examples",
    "Noun",
    "Expression",
    "Homophones",
    "Prefix",
    "Synonyms",
    "Symbol",
    "Initialism",
    "Abbreviation",
    "Suffix",
    "Contraction",
    "Notes",
    "Conjunction",
    "Antonym",
    "Phrases",
    "Antonyms",
    "Gallery",
    "Adverb",
    "Determiner",
    "Usage",
    "Synonym",
    "Acronym",
    "Interjection",
    "Determinative",
    "Preposition",
    "Adjective",
    "Etymology",
    "Pronoun",
    "Phrase",
    "Verb",
    "Numerals",
    "Pronunciation"
  )
}
