case class SimpleWiktionary(text: String,
                            examples: String,
                            noun: String,
                            expression: String,
                            homophones: String,
                            prefix: String,
                            synonyms: String,
                            symbol: String,
                            initialism: String,
                            abbreviation: String,
                            suffix: String,
                            contraction: String,
                            notes: String,
                            conjunction: String,
                            antonym: String,
                            phrases: String,
                            antonyms: String,
                            gallery: String,
                            adverb: String,
                            determiner: String,
                            usage: String,
                            synonym: String,
                            acronym: String,
                            interjection: String,
                            determinative: String,
                            preposition: String,
                            adjective: String,
                            etymology: String,
                            pronoun: String,
                            phrase: String,
                            verb: String,
                            numerals: String,
                            pronunciation: String)

object SimpleWiktionary {
  val partsOfSpeech: List[String] = List(
    "abbreviation",
    "acronym",
    "adjective",
    "adjective 1",
    "adverb",
    "auxiliary verb",
    "compound determinative",
    "conjunction",
    "contraction",
    "coordinator",
    "demonstrative determiner",
    "determinative",
    "determiner",
    "expression",
    "initialism", // basically acronym
    "interjection",
    "noun",
    "noun 1",
    "noun 2",
    "noun 3",
    "prefix",
    "preposition",
    "pronoun",
    "proper noun",
    "subordinator",
    "suffix",
    "symbol",
    "verb",
    "verb 1",
    "verb 2"
  )

  val metaSections = List("pronunciation", "usage", "usage notes")
}
