case class SimpleWiktionary(text: String,
                            examples: String,
                            noun: String,
                            expression: String,
                            homophones: String,
                            prefix: String,
                            synonyms: String,
                            symbol: String,
                            initialism: String,
                            abbreviation: String,
                            suffix: String,
                            contraction: String,
                            notes: String,
                            conjunction: String,
                            antonym: String,
                            phrases: String,
                            antonyms: String,
                            gallery: String,
                            adverb: String,
                            determiner: String,
                            usage: String,
                            synonym: String,
                            acronym: String,
                            interjection: String,
                            determinative: String,
                            preposition: String,
                            adjective: String,
                            etymology: String,
                            pronoun: String,
                            phrase: String,
                            verb: String,
                            numerals: String,
                            pronunciation: String)

object SimpleWiktionary {
  val sectionNames: List[String] = List(
    "abbreviation",
    "acronym",
    "adjective",
    "adjective 1",
    "adverb",
    "alternative forms",
    "anagrams",
    "antonyms",
    "auxiliary verb",
    "compound determinative",
    "conjunction",
    "contraction",
    "coordinator",
    "demonstrative determiner",
    "derived terms",
    "derived words",
    "determinative",
    "determiner",
    "english",
    "etymology",
    "expression",
    "gallery",
    "initialism",
    "interjection",
    "notes",
    "noun",
    "noun 1",
    "noun 2",
    "noun 3",
    "number",
    "numerals",
    "other forms",
    "other spellings",
    "other websites",
    "phrase",
    "prefix",
    "preposition",
    "pronoun",
    "pronunciation",
    "proper noun",
    "subordinator",
    "suffix",
    "symbol",
    "synonyms",
    "usage",
    "usage notes",
    "verb",
    "verb 1",
    "verb 2",
    "verb phrase subordinator"
  )

}
