apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cluster-wide services

# nginx proxy for traffic into the cluster
- ingress/ingress.yml
- certificate/cert-manager.yml
- certificate/letsencrypt-staging.yml
- certificate/letsencrypt-prod.yml

# Elasticsearch - used for logs and language content storage
- elasticsearch/elasticsearch-service.yml

# Microservices

- api/service.yml
- api/deployment.yml
- api/autoscale.yml

- language-service/service.yml
- language-service/deployment.yml
- language-service/autoscale.yml

# Scheduled jobs

# Used to get permission to download containers from the Amazon container registry
- ecr-cred-helper/service-account-binding.yml
- ecr-cred-helper/service-account.yml
- ecr-cred-helper/task.yml
