apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment/language-service.yml
- services/language-service.yml
- ecr-cred-helper/service-account-binding.yml
- ecr-cred-helper/service-account.yml
- ecr-cred-helper/task.yml
