version: '3'
services:
  api:
    build: .
    links:
      - database
    ports:
      - "4000:4000"
  database:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      3306:3306
