version: '3'
services:
  api:
    build: .
    links:
      - database
    ports:
      - "4000:4000"
  database:
    image: "mysql:5.7"
    env:
      MYSQL_USER: dev-user
      MYSQL_PASSWORD: dev-password
      MYSQL_DATABASE: foreign-language-reader
    ports:
    - 33061:3306
