version: '3'
services:
  api:
    build: .
    environment:
      DATABASE_URL: "ecto://dev-user:dev-password@database:3306/foreign-language-reader"
      SECRET_KEY_BASE: "KN4rxjPOfxRk3uo7fD928e6nt12jzrvy5t90fp7Snlp63ckc0rRZTglirGt+WiB6"
    ports:
      - "4000:4000"
  database:
    image: "mysql:5.7"
    environment:
      MYSQL_USER: dev-user
      MYSQL_PASSWORD: dev-password
      MYSQL_DATABASE: foreign-language-reader
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
    - 33061:3306
