name: API PR Review

on: 
  pull_request:
    paths: "api/*"
    types: closed
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Move build files to root of build worker
      run: |
        shopt -s dotglob
        mv api/* .
    - uses: actions/setup-node@v1
      name: Install node 12
      with:
        node-version: '12.x'
    - name: npm install
      run: |
        npm ci
      env:
        CI: true
    - name: Set up serverless
      run: npm install -g serverless
    - name: Build deployment package
      run: serverless package --package build
