name: API V2 PR Review

on:
  pull_request:
    paths:
      - "api-v2/*"
      - "api-v2/**/*"
      - "domain/*"
      - "domain/**/*"
      - "dto/*"
      - "dto/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build container
      run: docker build .