name: Baseline
# Pull requests are judged by how they impact coverage and security.
# This sets the baseline so we can see the impact of each individual pull request by comparing it against main.

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Scala code coverage
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK 15
      uses: actions/setup-java@v3.2.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'
    - name: Compile
      run: sbt compile
    - name: Run tests
      run: sbt coverage test
    - name: Enforce coverage
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        flags: unittest

  # This needs a main reference, not a closed pull request reference. Keep it here.
  security:
    runs-on: ubuntu-latest
    name: Security scan
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Login to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Why do we do this here instead of in the docker image?
    # It's because github package repository needs auth
    # And we DO NOT want that auth inside the docker image
    - name: Download dependencies
      run: |
        mv build.sbt build-real-sbt
        mv build-dependencies build.sbt
        sbt compile
        cp -r ~/.cache/coursier/v1/ ./coursier_cache
        mv build.sbt build-dependencies
        mv build-real-sbt build.sbt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Do this in case they have changed
    # Pulling is there for caching, in case nothing has changed
    # Remember not to push
    - name: Build dependencies image
      run: |
        docker build . -f Dockerfile_base -t lkjaero/foreign-language-reader-api:base
        docker build . -f Dockerfile_builder -t lkjaero/foreign-language-reader-api:builder

    - name: Build container
      run: docker build . -t api

    - name: Container security scan
      id: scan
      uses: anchore/scan-action@v3
      with:
        image: "api:latest"
        acs-report-enable: true

    - name: Upload scan report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }} 