name: PR Review

on: 
  pull_request:
    paths: "frontend/*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        path: repo
    - name: Display directory names
      run: ls -la && ls -la repo 
    - uses: actions/setup-node@v1
      name: Install node 12
      with:
        node-version: '12.x'
    - name: npm install, build, and test
      run: |
        npm ci
      env:
        CI: true
    - name: Validate security of dependencies
      run: npx audit-ci --moderate
    - name: Lint
      run: npm run lint
    - name: build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
