name: Jobs PR Review

on:
  pull_request:
    paths:
      - "content/*"
      - "content/**/*"
      - "jobs/*"
      - "jobs/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14.0.1'
    - name: Build jar
      run: sbt jobs/package