name: Jobs PR Review

on: [pull_request]

jobs:
  build:
    name: Confirm that the fat jar builds
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up JDK 15
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 15.0.1

    - name: Build jar
      run: sbt assembly