name: Master baselines

on:
  push:
    branches:
      - master

jobs:
  scala:
    name: Scala code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Load SBT cache
      uses: coursier/cache-action@v3
    - name: Compile
      run: sbt compile
    - name: Run tests
      run: sbt coverage test
    - name: Enforce coverage
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittest
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: api/target/scala-2.11/coverage-report/cobertura.xml, content/target/scala-2.11/coverage-report/cobertura.xml, domain/target/scala-2.11/coverage-report/cobertura.xml, jobs/target/scala-2.11/coverage-report/cobertura.xml

  api:
    runs-on: ubuntu-latest
    name: API baseline security scan
    steps:
      - uses: actions/checkout@v1

      - name: Build container
        run: docker build . -t api

      - name: Container security scan
        id: scan
        uses: anchore/scan-action@v2
        with:
          image: "api:latest"
          fail-build: true
          acs-report-enable: true

      - name: Upload scan report
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}