name: Codecov

on:
  push:
    branches:
      - master

jobs:
  api:
    name: Scala code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '14.0.1'
    - name: Run tests
      run: sbt coverage test
    - name: Enforce coverage
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittest