name: Release

on:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Scala code coverage
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.1
    - name: Load SBT cache
      uses: coursier/cache-action@v3
    - name: Compile
      run: sbt compile
    - name: Run tests
      run: sbt coverage test
    - name: Enforce coverage
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittest
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: api/target/scala-2.12/coverage-report/cobertura.xml, content/target/scala-2.12/coverage-report/cobertura.xml, domain/target/scala-2.12/coverage-report/cobertura.xml, jobs/target/scala-2.12/coverage-report/cobertura.xml

  security:
    runs-on: ubuntu-latest
    name: Security scan
    steps:
      - uses: actions/checkout@v1

      - name: Build container
        run: docker build . -t api

      - name: Container security scan
        id: scan
        uses: anchore/scan-action@v2
        with:
          image: "api:latest"
          fail-build: true
          acs-report-enable: true

      - name: Upload scan report
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    needs: [coverage, security]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.1
      - name: Load SBT cache
        uses: coursier/cache-action@v3
      - name: Publish
        run: sbt release with-defaults
