name: Test definition refresh

on:
  pull_request:
    paths:
      - "content/definitions/refresh-definitions/*"
      - "content/definitions/refresh-definitions/**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Move build files to root of build worker
      run: |
        shopt -s dotglob
        mv content/definitions/refresh-definitions/* .

    - name: Build container
      run: docker build .
