name: Release

on:
  pull_request:
    types: [ closed ]
    branches: master

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.1
      - name: Configure git
        run: |
          git config --local user.email "release@foreignlanguagereader.com"
          git config --local user.name "Release"
      - name: Publish
        run: sbt "release with-defaults"
