on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Update dependencies

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    env:
      # Required for the sbt-release plugin to work.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD_REPOSITORY_TOKEN }}
          author-email: lucas@lucaskjaero.com