name: Deploy vocabulary lambda

on:
  pull_request:
    paths: "vocabulary/*"
    paths-ignore: "**.tf"
    types: closed
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Move build files to root of build worker
      run: |
        shopt -s dotglob
        mv vocabulary/* .

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install python-lambda
      run: pip install python-lambda

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy with python-lambda
      run: lambda deploy
